services:
 rabbitmq:
  image: rabbitmq:3-management
  container_name: rabbitmq
  hostname: my-rabbitmq
  restart: always
  ports:
   - 5672:5672
   - 15672:15672
  volumes:
   - ./RabbitMQData:/var/lib/rabbitmq/
  environment:
   - RABBITMQ_DEFAULT_USER=ademe
   - RABBITMQ_DEFAULT_PASS=123456
